#!/bin/bash
VERBOS=0

# Detect -v flag
for arg in "$@"; do
    if [ "$arg" = "-v" ]; then
        VERBOS=1
    elif [ "$arg" = "-V" ]; then
        VERBOS=2
    fi
done

# Remove -v flag from arguments
ARGS=()
for arg in "$@"; do
    if [ "$arg" != "-v" ]; then
        ARGS+=("$arg")
    elif [ "$arg" != "-V" ]; then
        ARGS+=("$arg")
    fi
done

if [ $# -ge 1 ]; then
    [ "$VERBOS" -ge 2 ] && echo "build object code..."
    nasm -f elf32 "$1" -o program.o
    [ "$VERBOS" -ge 2 ] && echo "done"
    [ "$VERBOS" -ge 2 ] && echo "linking..."
    ld -m elf_i386 program.o -o program.elf
    [ "$VERBOS" -ge 2 ] && echo "done"
    [ "$VERBOS" -ge 2 ] && echo "removing object code"
    rm program.o
    [ "$VERBOS" -ge 2 ] && echo "executing program"
    [ "$VERBOS" -ge 1 ] && echo ""
    [ "$VERBOS" -ge 1 ] && echo "==================================="
    ./program.elf
    [ "$VERBOS" -ge 1 ] && echo "==================================="
    [ "$VERBOS" -ge 1 ] && echo "Program exited with exit code $?"
    [ "$VERBOS" -ge 1 ] && echo ""
else
    echo "Usage: $0 <asm-file>"
    echo "Usage (use with verbos level 1): $0 <asm-file> -v"
    echo "Usage (use with verbos level 2): $0 <asm-file> -V"
    echo "Please provide an assembly file as the first argument."
fi
